package com.proschedule.core.persistence.view.set;

import com.proschedule.core.persistence.exceptions.SetPersistenceException;
import com.proschedule.util.combobox.NumberOperatorComboBoxModel;
import com.proschedule.util.combobox.StringOperatorComboBoxModel;
import com.proschedule.util.messages.MessageDialog;
import com.proschedule.util.search.ISearchDialog;
import com.proschedule.util.search.SearchParam;

/**
 *
 * @author Maycon Bordin
 */
public class SetSearchDialog extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private SetTableModel setTableModel;
    private SetController controller;
    private ISearchDialog dialog;

    private SetFieldComboBoxModel setFieldComboBoxModel;
    private StringOperatorComboBoxModel stringOperatorComboBoxModel;
    private NumberOperatorComboBoxModel numberOperatorComboBoxModel;

    /**
     * Construtor da Classe
     * 
     * @param parent frame principal
     * @param dialog Adaptador do diálogo que receberá valor selecionado na busca
     */
    public SetSearchDialog(java.awt.Frame parent, ISearchDialog dialog) {
        super(parent, true);
        this.parent = parent;
        this.dialog = dialog;
        startUp();
    }

    /**
     * Inicia as configurações, componentens, variáveis
     */
    public void startUp() {
        controller = new SetController();

        initComponents();
        
        //Carrega o table model
        loadSetTableModel();

        //Carrega a barra de busca
        loadSearchBar();

        //Centraliza o diálogo
        setLocationRelativeTo(null);

        setTitle("Buscar Conjunto");
    }

    /**
     * Carrega a barra de busca de conjuntos
     */
    public void loadSearchBar() {
        setFieldComboBoxModel = new SetFieldComboBoxModel();
        stringOperatorComboBoxModel = new StringOperatorComboBoxModel();

        jcbField.setModel(setFieldComboBoxModel);
        jcbOperator.setModel(stringOperatorComboBoxModel);

        jcbField.setSelectedIndex(0);
        jcbOperator.setSelectedIndex(0);
    }

    /**
     * Recarrega a posição padrão da barra de busca
     */
    public void reloadSearchBar() {
        jcbField.setSelectedIndex(0);
        jcbOperator.setSelectedIndex(0);
        jtfValue.setText(null);
    }

    /**
     * Carrega a tabela de conjuntos, listando todos os registros existentes
     */
    public void loadSetTableModel() {
        try {
            setTableModel = new SetTableModel( controller.getSets() );
            jtSets.setModel(setTableModel);
        } catch (SetPersistenceException ex) {
            MessageDialog.error(ex, parent);
        }
    }

    /**
     * Carrega o objeto selecionado no controlador
     *
     * @return True se um objeto foi selecionado ou false se não havia objeto selecionado
     */
    public boolean loadSelectedSet() {
        int index = jtSets.getSelectedRow();

        if ( index != -1 ) {
            //Seta o conjunto selecionado para edição
            controller.editSet( setTableModel.getSet( index ) );
            return true;
        } else {
            MessageDialog.error("É preciso selecionar um conjunto para fazer isso!", parent);
        }

        return false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspSets = new javax.swing.JScrollPane();
        jtSets = new javax.swing.JTable();
        jbClearSearch = new javax.swing.JButton();
        jbGoSearch = new javax.swing.JButton();
        jtfValue = new javax.swing.JTextField();
        jcbOperator = new javax.swing.JComboBox();
        jcbField = new javax.swing.JComboBox();
        jlSearchingFor = new javax.swing.JLabel();
        jbSelect = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtSets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtSets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSetsMouseClicked(evt);
            }
        });
        jspSets.setViewportView(jtSets);

        jbClearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/clear_16.png"))); // NOI18N
        jbClearSearch.setToolTipText("Limpar Busca");
        jbClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearSearchActionPerformed(evt);
            }
        });

        jbGoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/search_16.png"))); // NOI18N
        jbGoSearch.setToolTipText("Buscar");
        jbGoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGoSearchActionPerformed(evt);
            }
        });

        jlSearchingFor.setText("Buscar por");

        jbSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/accept.png"))); // NOI18N
        jbSelect.setText("Selecionar");
        jbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectActionPerformed(evt);
            }
        });

        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/close.png"))); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspSets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSearchingFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbClearSearch)
                    .addComponent(jbGoSearch)
                    .addComponent(jtfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSearchingFor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspSets, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbSelect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtSetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSetsMouseClicked
        //Clique duplo
        if (evt.getClickCount() == 2) {
            if ( loadSelectedSet() ) {
                dialog.selectItem( controller.getSet() );
                dispose();
            }
        }
}//GEN-LAST:event_jtSetsMouseClicked

    private void jbClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearSearchActionPerformed
        loadSetTableModel();
        reloadSearchBar();
}//GEN-LAST:event_jbClearSearchActionPerformed

    private void jbGoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGoSearchActionPerformed
        try {
            SearchParam field = (SearchParam) jcbField.getSelectedItem();
            SearchParam operator = (SearchParam) jcbOperator.getSelectedItem();

            if ( field.getName().equals("id") ) {
                String value = jtfValue.getText();
                setTableModel = new SetTableModel( controller.getSets(field, value, operator) );
            }

            jtSets.setModel(setTableModel);
        } catch (SetPersistenceException ex) {
            MessageDialog.error(ex, parent);
        } catch (NullPointerException ex) {
            MessageDialog.error("É preciso preencher todos os valores para a busca.", ex.toString(), parent);
        }
}//GEN-LAST:event_jbGoSearchActionPerformed

    private void jbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectActionPerformed
        if ( loadSelectedSet() ) {
            dialog.selectItem( controller.getSet() );
            dispose();
        }
}//GEN-LAST:event_jbSelectActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        dispose();
}//GEN-LAST:event_jbCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbClearSearch;
    private javax.swing.JButton jbGoSearch;
    private javax.swing.JButton jbSelect;
    private javax.swing.JComboBox jcbField;
    private javax.swing.JComboBox jcbOperator;
    private javax.swing.JLabel jlSearchingFor;
    private javax.swing.JScrollPane jspSets;
    private javax.swing.JTable jtSets;
    private javax.swing.JTextField jtfValue;
    // End of variables declaration//GEN-END:variables

}
