/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on Nov 21, 2010, 12:49:55 PM
 */

package com.proschedule.main.view;

import com.proschedule.main.ProSchedule;

/**
 * Diálogo sobre o sistema
 * 
 * @author Maycon Bordin
 * @version 1.0
 * @created 04-out-2010 13:24:50
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Construtor da Classe
     * 
     * @param parent Painel principal
     */
    public AboutDialog(java.awt.Frame parent) {
        super(parent, true);
        startUp();
    }

    /**
     * Inicializa componentes e variáveis
     */
    public void startUp() {
        initComponents();

        setTitle("Sobre");

        //Centraliza o diálogo
        setLocationRelativeTo(null);

        loadInfo();
    }

    /**
     * Carrega as informações do sistema
     */
    public void loadInfo() {
        String info = "";

        info += "<strong>Versão do Produto:</strong> " + ProSchedule.getSystemTitle();
        info += "<br><strong>Java:</strong> " + System.getProperty("java.version") + "; "
                + System.getProperty("java.vm.name") + " " + System.getProperty("java.vm.version");
        info += "<br><strong>Sistema Operacional:</strong> " + System.getProperty("os.name") + " " +
                System.getProperty("os.version") + " " + System.getProperty("os.arch");

        jepInfo.setText(info);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLogo = new javax.swing.JLabel();
        jspInfo = new javax.swing.JScrollPane();
        jepInfo = new javax.swing.JEditorPane();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jlLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/brand/splash_logo.png"))); // NOI18N

        jepInfo.setContentType("text/html");
        jspInfo.setViewportView(jepInfo);

        jbClose.setText("Fechar");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                            .addComponent(jlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jbClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo)
                .addGap(18, 18, 18)
                .addComponent(jspInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jbCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClose;
    private javax.swing.JEditorPane jepInfo;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JScrollPane jspInfo;
    // End of variables declaration//GEN-END:variables

}
