package com.proschedule.main.view;

import com.proschedule.main.ProSchedule;
import com.proschedule.main.ProScheduleException;
import com.proschedule.util.messages.MessageDialog;

/**
 * Diálogo para confirmação de fechamento do sistema
 * 
 * @author Maycon Bordin
 * @version 1.0
 * @created 04-out-2010 13:24:50
 */
public class CloseAppDialog extends javax.swing.JDialog {

    private MainFrame parent;

    /**
     * Construtor da Classe
     * @param parent Painel principal
     */
    public CloseAppDialog(java.awt.Frame parent) {
        super(parent, true);
        this.parent = (MainFrame) parent;
        startUp();
    }

    /**
     * Inicializa componentes e variáveis
     */
    public void startUp() {
        initComponents();
        
        //Centraliza o diálogo
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlText = new javax.swing.JLabel();
        jcbExitWithoutAsk = new javax.swing.JCheckBox();
        jbCancel = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmar Saída");

        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/messages/question.png"))); // NOI18N

        jlText.setText("Deseja realmente sair do ProSchedule?");

        jcbExitWithoutAsk.setText("Não perguntar novamente");

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlText))
                    .addComponent(jcbExitWithoutAsk))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlIcon)
                    .addComponent(jlText))
                .addGap(18, 18, 18)
                .addComponent(jcbExitWithoutAsk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        try {
            if (jcbExitWithoutAsk.isSelected()) {
                ProSchedule.setConfig("system.close_without_ask", "true");
            }
            parent.dispose();
            ProSchedule.exit(0);
        } catch (ProScheduleException ex) {
            MessageDialog.error(ex.getMessage(), ex.getDetailMessage(), parent);
        }
    }//GEN-LAST:event_jbOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JCheckBox jcbExitWithoutAsk;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlText;
    // End of variables declaration//GEN-END:variables

}
