package com.proschedule.core.persistence.view.customer;

import com.proschedule.core.persistence.exceptions.CustomerPersistenceException;
import com.proschedule.util.combobox.StringOperatorComboBoxModel;
import com.proschedule.util.messages.MessageDialog;
import com.proschedule.util.search.ISearchDialog;
import com.proschedule.util.search.SearchParam;

/**
 * Diálogo de busca de clientes. Implementando um adaptador através da interface
 * ISearchDialog é possível efetuar a comunicação com o diálogo, permitindo que ele
 * envie o objeto Cliente selecionado.
 *
 * @author Maycon Bordin
 * @version 1.0
 * @created 04-out-2010 13:24:49
 */
public class CustomerSearchDialog extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private CustomerTableModel customerTableModel;
    private CustomerPresenter presenter;
    private ISearchDialog dialog;

    private CustomerFieldComboBoxModel customerFieldComboBoxModel;
    private StringOperatorComboBoxModel stringOperatorComboBoxModel;

    /**
     * Construtor da Classe
     *
     * @param parent Frame principal
     * @param dialog Adaptador para comunicação
     */
    public CustomerSearchDialog(java.awt.Frame parent, ISearchDialog dialog) {
        super(parent, true);
        this.parent = parent;
        this.dialog = dialog;
        startUp();
    }

    /**
     * Inicializa as configurações e componentes
     */
    public void startUp() {
        presenter = new CustomerPresenter();

        //Carrega o table model
        loadCustomerTableModel();

        initComponents();

        //Carrega a barra de busca
        loadSearchBar();

        //Centraliza o diálogo
        setLocationRelativeTo(null);

        setTitle("Buscar Cliente");
    }

    /**
     * Carrega a barra de busca de clientes
     */
    public void loadSearchBar() {
        customerFieldComboBoxModel = new CustomerFieldComboBoxModel();
        stringOperatorComboBoxModel = new StringOperatorComboBoxModel();

        jcbField.setModel(customerFieldComboBoxModel);
        jcbOperator.setModel(stringOperatorComboBoxModel);

        jcbField.setSelectedIndex(0);
        jcbOperator.setSelectedIndex(0);
    }

    /**
     * Recarrega a posição padrão da barra de busca
     */
    public void reloadSearchBar() {
        jcbField.setSelectedIndex(0);
        jcbOperator.setSelectedIndex(0);
        jtfValue.setText(null);
    }

    /**
     * Carrega a tabela de clientes, listando todos os registros existentes
     */
    public void loadCustomerTableModel() {
        try {
            presenter.loadCustomers();
            customerTableModel = new CustomerTableModel( presenter.getCustomers() );
        } catch (CustomerPersistenceException ex) {
            MessageDialog.error(ex, parent);
        }
    }

    /**
     * Recarrega a tabela de clientes. É usado quando modificações são efetuadas
     * em algum registro.
     */
    public void reloadCustomerTableModel() {
        try {
            presenter.loadCustomers();
            customerTableModel = new CustomerTableModel( presenter.getCustomers() );
            jtCustomers.setModel(customerTableModel);
        } catch (CustomerPersistenceException ex) {
            MessageDialog.error(ex, parent);
        }
    }

    /**
     * Carrega no presenter o registro selecionado na tabela de clientes
     *
     * @return True se houver um registro selecionado ou falso se nada foi selecionado
     */
    public boolean loadSelectedRow() {
        int index = jtCustomers.getSelectedRow();

        if ( index != -1 ) {
            //Seta o cliente selecionado para edição
            presenter.setCustomer( customerTableModel.getCustomer( index ) );

            return true;
        } else {
            MessageDialog.error("É preciso selecionar um cliente para fazer isso!", parent);
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspCustomers = new javax.swing.JScrollPane();
        jtCustomers = new javax.swing.JTable();
        jlSearchingFor = new javax.swing.JLabel();
        jcbField = new javax.swing.JComboBox();
        jcbOperator = new javax.swing.JComboBox();
        jtfValue = new javax.swing.JTextField();
        jbGoSearch = new javax.swing.JButton();
        jbClearSearch = new javax.swing.JButton();
        jbSelect = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtCustomers.setModel(customerTableModel);
        jtCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCustomersMouseClicked(evt);
            }
        });
        jspCustomers.setViewportView(jtCustomers);

        jlSearchingFor.setText("Buscar por");

        jbGoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/search_16.png"))); // NOI18N
        jbGoSearch.setToolTipText("Buscar");
        jbGoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGoSearchActionPerformed(evt);
            }
        });

        jbClearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/clear_16.png"))); // NOI18N
        jbClearSearch.setToolTipText("Limpar Busca");
        jbClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearSearchActionPerformed(evt);
            }
        });

        jbSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/accept.png"))); // NOI18N
        jbSelect.setText("Selecionar");
        jbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectActionPerformed(evt);
            }
        });

        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proschedule/resources/images/forms/close.png"))); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSearchingFor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbClearSearch)
                    .addComponent(jbGoSearch)
                    .addComponent(jtfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSearchingFor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbSelect))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jspCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Seleciona o cliente quando um clique duplo for acionado
     * 
     * @param evt
     */
    private void jtCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCustomersMouseClicked
        //Clique duplo
        if (evt.getClickCount() == 2) {
            if ( loadSelectedRow() ) {
                dialog.selectItem( presenter.getCustomer() );
                dispose();
            }
        }
}//GEN-LAST:event_jtCustomersMouseClicked

    /**
     * Realiza a busca de acordo com os parâmetros informados e lista-os na tabela
     * de clientes.
     *
     * @param evt
     */
    private void jbGoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGoSearchActionPerformed
        try {
            SearchParam field = (SearchParam) jcbField.getSelectedItem();
            String value = jtfValue.getText();
            SearchParam operator = (SearchParam) jcbOperator.getSelectedItem();

            presenter.loadCustomers(field, value, operator);
            customerTableModel = new CustomerTableModel( presenter.getCustomers() );
            jtCustomers.setModel(customerTableModel);
        } catch (CustomerPersistenceException ex) {
            MessageDialog.error(ex, parent);
        } catch (NullPointerException ex) {
            MessageDialog.error("É preciso preencher todos os valores para a busca.", ex.toString(), parent);
        }
}//GEN-LAST:event_jbGoSearchActionPerformed

    /**
     * Limpa da tabela a busca realizada.
     *
     * @param evt
     */
    private void jbClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearSearchActionPerformed
        reloadCustomerTableModel();
        reloadSearchBar();
}//GEN-LAST:event_jbClearSearchActionPerformed

    /**
     * Repassa para o adaptador o objeto selecionado da lista
     *
     * @param evt
     */
    private void jbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectActionPerformed
        if ( loadSelectedRow() ) {
            dialog.selectItem( presenter.getCustomer() );
            dispose();
        }
}//GEN-LAST:event_jbSelectActionPerformed

    /**
     * Fecha o diálogo
     *
     * @param evt
     */
    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        dispose();
}//GEN-LAST:event_jbCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbClearSearch;
    private javax.swing.JButton jbGoSearch;
    private javax.swing.JButton jbSelect;
    private javax.swing.JComboBox jcbField;
    private javax.swing.JComboBox jcbOperator;
    private javax.swing.JLabel jlSearchingFor;
    private javax.swing.JScrollPane jspCustomers;
    private javax.swing.JTable jtCustomers;
    private javax.swing.JTextField jtfValue;
    // End of variables declaration//GEN-END:variables

}
